# Lab_2
# Работа с библиотеками NumPy , pandas

In [1]:
import numpy as np

my_array = np.arange(5, 101, 5)
my_array

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [2]:
#2
my_array_10 = my_array[my_array % 10 == 0]
my_array_10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [3]:
#3
two_column_array = my_array_10.reshape(-1, 2)
two_column_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [4]:
#4
my_second_array = two_column_array[:] - 5
my_second_array

array([[ 5, 15],
       [25, 35],
       [45, 55],
       [65, 75],
       [85, 95]])

In [7]:
#5
combined_array = np.hstack((two_column_array, my_second_array))
combined_array

array([[ 10,  20,   5,  15],
       [ 30,  40,  25,  35],
       [ 50,  60,  45,  55],
       [ 70,  80,  65,  75],
       [ 90, 100,  85,  95]])

In [8]:
two_column_array = two_column_array.T
two_column_array

array([[ 10,  30,  50,  70,  90],
       [ 20,  40,  60,  80, 100]])

In [9]:
combined_array = combined_array.T
combined_array

array([[ 10,  30,  50,  70,  90],
       [ 20,  40,  60,  80, 100],
       [  5,  25,  45,  65,  85],
       [ 15,  35,  55,  75,  95]])

In [13]:
#6
combined_array[1] = combined_array[1] / two_column_array[0]
combined_array[2] = combined_array[2] / two_column_array[1]
combined_array

array([[10, 30, 50, 70, 90],
       [ 2,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0],
       [15, 35, 55, 75, 95]])

In [14]:
#7
new_combined_array = np.delete(combined_array, np.where(np.any(combined_array < 3, axis=1)), axis=0)
new_combined_array

array([[10, 30, 50, 70, 90],
       [15, 35, 55, 75, 95]])

In [15]:
new_array = np.hstack((two_column_array.T, my_second_array))
new_array = np.resize(new_array, (3, 4))
print("До изменения:\n",new_array)
new_array[0], new_array[2] = new_array[2].copy(), new_array[0].copy()
print("После изменения:\n",new_array)

До изменения:
 [[10 20  5 15]
 [30 40 25 35]
 [50 60 45 55]]
После изменения:
 [[50 60 45 55]
 [30 40 25 35]
 [10 20  5 15]]


In [20]:
medians = np.median(new_array, axis=0)
means = np.mean(new_array, axis=0)
stds = np.std(new_array, axis=0)
print("Медианы:",medians)
print("Среднее:",means)
print("Отклонения:",stds)

Медианы: [30. 40. 25. 35.]
Среднее: [30. 40. 25. 35.]
Отклонения: [16.32993162 16.32993162 16.32993162 16.32993162]


In [21]:
max_values = np.max(new_array, axis=1, keepdims=True)
normalized_array = new_array / max_values
normalized_array

array([[0.83333333, 1.        , 0.75      , 0.91666667],
       [0.75      , 1.        , 0.625     , 0.875     ],
       [0.5       , 1.        , 0.25      , 0.75      ]])

# Pandas

In [32]:
import pandas as pd

df = pd.read_csv('Global Population Trends(2016-2022).csv')
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55            63.0      37.342       7.027   
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38            61.0      32.516       8.266   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[1073 rows x 12 columns]

In [33]:
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

In [34]:
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

In [35]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


In [37]:
for column in df.columns:
    df = df[df[column]!='-']

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 561 entries, 1 to 1071
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                561 non-null    object 
 1   Year                   561 non-null    int64  
 2   Total Population       561 non-null    object 
 3   Urban Population       561 non-null    object 
 4   Rural Population       561 non-null    object 
 5   Population Density     561 non-null    object 
 6   Life Expectancy        561 non-null    object 
 7   Birth Rate             561 non-null    float64
 8   Death Rate             561 non-null    float64
 9   Fertility Rate         561 non-null    object 
 10  Infant Mortality Rate  561 non-null    object 
 11  Growth Rate            561 non-null    object 
dtypes: float64(2), int64(1), object(9)
memory usage: 57.0+ KB


In [39]:
df1 = df[df['Total Population'] != '-']
df1.describe()

Year  Birth Rate  Death Rate
count   561.000000  561.000000  561.000000
mean   2019.000000   19.964579    7.893127
std       0.817225    9.869139    2.768170
min    2018.000000    5.300000    0.982000
25%    2018.000000   11.000000    6.103000
50%    2019.000000   17.832000    7.373000
75%    2020.000000   28.038000    9.330000
max    2020.000000   46.127000   18.000000

In [41]:
sorted_df = df1.sort_values(by=['Year', 'Country'])
sorted_df

Country  Year Total Population Urban Population  \
1             Afghanistan  2018       36,686,784        9,353,296   
6                 Albania  2018        2,866,376        1,728,969   
11                Algeria  2018       41,927,007       30,451,166   
24                 Angola  2018       31,273,533       20,488,542   
29    Antigua And Barbuda  2018           91,626           22,539   
...                   ...   ...              ...              ...   
1046              Vietnam  2020       96,648,685       36,088,619   
1056   West Bank And Gaza  2020        4,803,269        3,685,020   
1061                Yemen  2020       32,284,046       12,238,236   
1066               Zambia  2020       18,927,715        8,447,250   
1071             Zimbabwe  2020       15,669,666        5,052,214   

     Rural Population Population Density Life Expectancy  Birth Rate  \
1          27,333,488                 56            63.0      36.927   
6           1,137,407                105            79.0      10.517   
11         11,475,841                 18            76.0      24.074   
24         10,784,991                 25            62.0      40.236   
29             69,087                208            79.0      10.816   
...               ...                ...             ...         ...   
1046       60,560,066                308            75.0      15.400   
1056        1,118,249                798            74.0      28.800   
1061       20,045,810                 61            65.0      31.252   
1066       10,480,465                 25            62.0      34.953   
1071       10,617,452                 41            61.0      31.009   

      Death Rate Fertility Rate Infant Mortality Rate Growth Rate  
1          6.981          5.002                  47.8         3.0  
6          8.308           1.44                   8.3         0.0  
11         4.482          3.023                  20.6         2.0  
24         7.990          5.519                  52.0         3.0  
29         5.787          1.371                   5.7         1.0  
...          ...            ...                   ...         ...  
1046       6.169          1.955                  16.6         1.0  
1056       3.489           3.57                  13.2         2.0  
1061       6.509          3.886                  45.8         2.0  
1066       6.602          4.379                  41.1         3.0  
1071       8.132          3.545                  36.6         2.0  

[561 rows x 12 columns]

In [47]:
sorted_df.to_excel("Global_Population_Trends_Sorted.xlsx", index=False)
sorted_df

Country  Year Total Population Urban Population  \
1             Afghanistan  2018       36,686,784        9,353,296   
6                 Albania  2018        2,866,376        1,728,969   
11                Algeria  2018       41,927,007       30,451,166   
24                 Angola  2018       31,273,533       20,488,542   
29    Antigua And Barbuda  2018           91,626           22,539   
...                   ...   ...              ...              ...   
1046              Vietnam  2020       96,648,685       36,088,619   
1056   West Bank And Gaza  2020        4,803,269        3,685,020   
1061                Yemen  2020       32,284,046       12,238,236   
1066               Zambia  2020       18,927,715        8,447,250   
1071             Zimbabwe  2020       15,669,666        5,052,214   

     Rural Population Population Density Life Expectancy  Birth Rate  \
1          27,333,488                 56            63.0      36.927   
6           1,137,407                105            79.0      10.517   
11         11,475,841                 18            76.0      24.074   
24         10,784,991                 25            62.0      40.236   
29             69,087                208            79.0      10.816   
...               ...                ...             ...         ...   
1046       60,560,066                308            75.0      15.400   
1056        1,118,249                798            74.0      28.800   
1061       20,045,810                 61            65.0      31.252   
1066       10,480,465                 25            62.0      34.953   
1071       10,617,452                 41            61.0      31.009   

      Death Rate Fertility Rate Infant Mortality Rate Growth Rate  
1          6.981          5.002                  47.8         3.0  
6          8.308           1.44                   8.3         0.0  
11         4.482          3.023                  20.6         2.0  
24         7.990          5.519                  52.0         3.0  
29         5.787          1.371                   5.7         1.0  
...          ...            ...                   ...         ...  
1046       6.169          1.955                  16.6         1.0  
1056       3.489           3.57                  13.2         2.0  
1061       6.509          3.886                  45.8         2.0  
1066       6.602          4.379                  41.1         3.0  
1071       8.132          3.545                  36.6         2.0  

[561 rows x 12 columns]