In [5]:
import numpy as np

a= np.empty(10, dtype='int64')
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [6]:
np.empty((3,2), dtype='int64')

array([[25895968444448860, 30962749956620365],
       [29555349301231732, 27303403461017710],
       [28429415035764846,     2628519985266]], dtype=int64)

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.ones([4,3], dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
np.full((3,2), -1)

array([[-1, -1],
       [-1, -1],
       [-1, -1]])